# Generated by Django 5.2.8 on 2025-11-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0002_appointmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('ophthalmology', 'Ophthalmology'), ('gynecology', 'Gynecology'), ('urology', 'Urology'), ('oncology', 'Oncology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('dental', 'Dental'), ('general', 'General Medicine'), ('other', 'Other')], max_length=50),
        ),
    ]
